language: go
env:
  global:
  - GO111MODULE=on
  - secure: CoEAy3SCtlsBeMzDguyyYNHNhn7q2EYVqPnO1vIzuFIqgsl8MA3WMzKQnPJjn73SRdYatEeyx/KoUIMsaYpJ++awJ0rFEBMRYihY+Qyz2DnVQVZs5q0pttLb+d6lPayjyxxHsicOxXFI56zSVTML2tdwRMgBQG2WNR9Zcpn/ttkaEWg3CSeP1DSvjcQ304bSWeWjkauyalDd1VWJv2XV6yqTc8xjpkhpo9atODVdCALiei2sO7H+KzxS9uYrRjHMUH3xEJMW3DmMRkbXoap7Z1dFUz3Vtnewx5S2ZviveqQqkVyBjy+A5zlhpqialLWUlyMQSu7p4RNhWFAh7T842sZjJ5GUU5ezKzrA2trdX8E0yMArMLTix3lWQ4XDRjf6BnDqQkLnRKQ/8DaIOtIDh7X9pVwT1+mg2vTVSl9+6vJD8rKd0YGQ63kA1+b+X2dxv2ovhwthMFSUPEB9xSIR5sgSg3hS1syCRmX0MUyap3t7bopDNNAQmpGBOSL+1WOiw4HDt74trwP9kvvSgSDje8YYUrNmOeXVcceyq15aBz+wLS24jGEbeErIbZd3O3eVaGVw0xxDOnFM3hmEhwyBhLQP4i9vJ8a7AFJrbu4NooVHEfmjqT8IDbBq1NWJYxfEjvuav89rHkjWVgazinvzsmY8wFZnz3er0zT6GXUmqdE=
jobs:
  include:
  - go: 1.10.x
    script: go test -v -race ./...
  - go: 1.11.x
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: go test -v -race -cover ./... -coverprofile=c.out
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
